# Generated by Django 5.2.1 on 2025-05-17 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Агент', 'verbose_name_plural': 'Агенты'},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='reporter_location',
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_building',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Корпус'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_department',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Подразделение'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Комната/Кабинет'),
        ),
    ]
