# Generated by Django 5.2.1 on 2025-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['project__name', 'name'], 'verbose_name': 'Категория тикета', 'verbose_name_plural': 'Категории тикетов'},
        ),
        migrations.AddField(
            model_name='ticketcategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Категория активна'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='agent_role',
            field=models.CharField(choices=[('agent', 'Агент проекта'), ('project_manager', 'Руководитель проекта')], default='agent', max_length=20, verbose_name='Роль в проектах'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Проекты, к которым сотрудник имеет доступ и в которых может работать.', related_name='agents', to='tickets.project', verbose_name='Проекты сотрудника'),
        ),
        migrations.AlterField(
            model_name='fieldtemplate',
            name='field_type',
            field=models.CharField(choices=[('char', 'Текстовое поле (короткое)'), ('text', 'Текстовое поле (длинное)'), ('email', 'Email'), ('int', 'Целое число'), ('bool', 'Да/Нет (чекбокс)'), ('date', 'Дата'), ('select', 'Выпадающий список'), ('file', 'Файл (вложение)')], max_length=20, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Неактивные проекты не будут отображаться для выбора и их тикеты могут быть скрыты.', verbose_name='Проект активен'),
        ),
    ]
