# Generated by Django 5.2.1 on 2025-05-17 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_agent_options_remove_ticket_reporter_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name_display', models.CharField(blank=True, max_length=255, verbose_name='Имя автора (для отображения)')),
                ('body', models.TextField(verbose_name='Текст комментария')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Внутренний комментарий (виден только агентам)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор (агент)')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Тикет')),
            ],
            options={
                'verbose_name': 'Комментарий к тикету',
                'verbose_name_plural': 'Комментарии к тикетам',
                'ordering': ['created_at'],
            },
        ),
    ]
