# Generated by Django 5.2.1 on 2025-05-22 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_role',
            field=models.CharField(choices=[('agent', 'Агент проекта'), ('project_manager', 'Руководитель проекта'), ('system_admin', 'Администратор системы')], default='agent', max_length=20, verbose_name='Роль в системе Helpdesk'),
        ),
    ]
