# Generated by Django 5.2.1 on 2025-05-23 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_agent_agent_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_role',
            field=models.CharField(choices=[('agent', 'Агент проекта'), ('project_manager', 'Руководитель проекта'), ('system_admin', 'Администратор системы')], default='agent', max_length=20, verbose_name='Роль в системе'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketpriority', verbose_name='Приоритет'),
        ),
    ]
