# Generated by Django 5.2.1 on 2025-05-17 02:38

import django.db.models.deletion
import tickets.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'Агент поддержки', 'verbose_name_plural': 'Агенты поддержки'},
        ),
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'ordering': ['name'], 'verbose_name': 'Категория тикета', 'verbose_name_plural': 'Категории тикетов'},
        ),
        migrations.AlterModelOptions(
            name='ticketpriority',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Приоритет тикета', 'verbose_name_plural': 'Приоритеты тикетов'},
        ),
        migrations.AlterModelOptions(
            name='ticketstatus',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Статус тикета', 'verbose_name_plural': 'Статусы тикетов'},
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin')], default='agent', max_length=10, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название категории'),
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=tickets.models.ticket_attachment_path, verbose_name='Файл')),
                ('uploaded_by_name_display', models.CharField(blank=True, max_length=255, verbose_name='Загрузил (имя для отображения)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.comment', verbose_name='Комментарий')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Тикет')),
                ('uploaded_by_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил (агент)')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
