# Generated by Django 5.2.1 on 2025-05-19 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_agent_options_alter_ticketcategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='support_line',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Первая линия'), (2, 'Вторая линия')], null=True, verbose_name='Линия поддержки'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='#CCCCCC', help_text='Например, #FF0000 для красного', max_length=7, verbose_name='Цвет статуса (HEX)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('agent', 'Agent'), ('admin', 'Admin')], default='agent', max_length=10, verbose_name='Роль доступа'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил (агент)'),
        ),
        migrations.AddConstraint(
            model_name='attachment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('ticket__isnull', False), ('comment__isnull', True)), models.Q(('ticket__isnull', True), ('comment__isnull', False)), models.Q(('ticket__isnull', False), ('comment__isnull', False)), _connector='OR'), name='either_ticket_or_comment_or_both_if_related'),
        ),
    ]
