# Generated by Django 5.2.1 on 2025-05-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_agent_agent_role_alter_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес автора комментария'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес заявителя'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.ticketpriority', verbose_name='Приоритет'),
        ),
    ]
