# Generated by Django 5.2.1 on 2025-05-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_agent_support_line_ticketstatus_color_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attachment',
            name='either_ticket_or_comment_or_both_if_related',
        ),
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('agent_l1', 'Агент L1'), ('agent_l2', 'Агент L2'), ('manager_l1', 'Руководитель L1'), ('manager_l2', 'Руководитель L2'), ('super_admin', 'Супер-Администратор')], default='agent_l1', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='support_line',
            field=models.IntegerField(blank=True, choices=[(1, 'Линия 1'), (2, 'Линия 2')], null=True, verbose_name='Линия поддержки'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.comment', verbose_name='Комментарий (если вложение к комментарию)'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Тикет (если вложение к тикету напрямую)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Цвет для отображения статуса, например, #4CAF50', max_length=7, verbose_name='Цвет (HEX)'),
        ),
    ]
