# Generated by Django 5.2.1 on 2025-05-20 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_attachment_either_ticket_or_comment_or_both_if_related_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_level',
            field=models.IntegerField(choices=[(1, 'Уровень 1 (L1)'), (2, 'Уровень 2 (L2)')], default=1, verbose_name='Уровень поддержки'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(blank=True, default='#CCCCCC', max_length=7, verbose_name='Цвет статуса (HEX)'),
        ),
    ]
