# Generated by Django 5.2.1 on 2025-05-20 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_ticket_ticket_level_alter_attachment_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketstatus',
            name='color',
        ),
        migrations.AddField(
            model_name='ticket',
            name='custom_form_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные дополнительных полей формы'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Внутренний комментарий'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id_display',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='ID тикета'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_closed_status',
            field=models.BooleanField(default=False, verbose_name="Статус 'Закрыт'"),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_default_status',
            field=models.BooleanField(default=False, verbose_name='Статус по умолчанию'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_resolved_status',
            field=models.BooleanField(default=False, verbose_name="Статус 'Решен'"),
        ),
        migrations.CreateModel(
            name='CustomFormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Используется в коде, должно быть уникальным в рамках категории. Только латиница, цифры, подчеркивания.', max_length=100, verbose_name='Имя поля (англ., для системы)')),
                ('label', models.CharField(max_length=255, verbose_name='Метка поля (для пользователя)')),
                ('field_type', models.CharField(choices=[('char', 'Текстовое поле (короткое)'), ('text', 'Текстовое поле (длинное)'), ('int', 'Целое число'), ('bool', 'Да/Нет (чекбокс)'), ('date', 'Дата'), ('select', 'Выпадающий список')], max_length=20, verbose_name='Тип поля')),
                ('is_required', models.BooleanField(default=False, verbose_name='Обязательное поле')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('help_text_custom', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подсказка для поля')),
                ('select_choices_json', models.JSONField(blank=True, help_text='Пример: {"val1": "Опция 1", "val2": "Опция 2"}', null=True, verbose_name='Варианты для выпадающего списка (JSON)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='tickets.ticketcategory', verbose_name='Категория тикета')),
            ],
            options={
                'verbose_name': 'Поле формы категории',
                'verbose_name_plural': 'Поля форм категорий',
                'ordering': ['category', 'order', 'label'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
