# Generated by Django 5.2.1 on 2025-05-21 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_remove_ticketstatus_color_ticket_custom_form_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['username'], 'verbose_name': 'Агент поддержки', 'verbose_name_plural': 'Агенты поддержки'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AddField(
            model_name='customformfield',
            name='can_be_deleted',
            field=models.BooleanField(default=True, help_text='Стандартные поля обычно нельзя удалять.', verbose_name='Можно удалять из настроек категории'),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно (отображать на форме)'),
        ),
        migrations.AddField(
            model_name='customformfield',
            name='is_standard',
            field=models.BooleanField(default=False, help_text='Отметьте, если это поле соответствует стандартному полю модели Ticket (например, title, description).', verbose_name='Стандартное поле модели Ticket'),
        ),
        migrations.AddField(
            model_name='ticketstatus',
            name='color',
            field=models.CharField(default='#777777', help_text='Например, #FF0000 для красного.', max_length=7, verbose_name='Цвет статуса (HEX)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='support_line',
            field=models.IntegerField(blank=True, choices=[(1, 'Линия 1'), (2, 'Линия 2')], help_text='Укажите линию поддержки для агентов и руководителей линий.', null=True, verbose_name='Линия поддержки'),
        ),
        migrations.AlterField(
            model_name='customformfield',
            name='field_type',
            field=models.CharField(choices=[('char', 'Текстовое поле (короткое)'), ('text', 'Текстовое поле (длинное)'), ('email', 'Email'), ('int', 'Целое число'), ('bool', 'Да/Нет (чекбокс)'), ('date', 'Дата'), ('select', 'Выпадающий список')], max_length=20, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='custom_form_data',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Данные дополнительных полей'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_closed_status',
            field=models.BooleanField(default=False, verbose_name='Этот статус означает, что тикет закрыт (финальный)'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_default_status',
            field=models.BooleanField(default=False, verbose_name='Статус по умолчанию для новых тикетов'),
        ),
        migrations.AlterField(
            model_name='ticketstatus',
            name='is_resolved_status',
            field=models.BooleanField(default=False, verbose_name='Этот статус означает, что проблема решена'),
        ),
    ]
